[package]
name = "chat_app"
version = "0.1.0"
authors = ["magey3 <magey3333@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
